parser/docwriter/docwriter.go

The docwriter's mongo session was being closed too early, so it would crash if one go routine finished ahead of others. This fix is critical for Ben's open pull request since the race condition is exacerbated by whitelist checking happening in the goroutines.

Fix race condition which may cause import to fail

---

Readme.md
etc/rita.yaml

I noticed a typo of "seperate" in the yaml so I grepped through the repo for that typo and fixed it.

Fix minor typos

---

Readme.md

The way the instructions are currently written, if you follow 5.vi, `mongod` will bind to all interfaces because a config file is not specified to apply the appropriate [net.bindIp](https://docs.mongodb.com/manual/reference/configuration-options/#net.bindIp) setting.
Option 1 (In PR):  Append ` -f /etc/mongod.conf` to `mongod --fork --logpath /data/mongod.log` in 5.vi
Option 2:  Replace steps 5.v and 5.vi with `systemctl start mongod` or `service mongod start`, which will also change the location of the log to `/var/log/mongodb/mongod.log` by default.  It also appears (at least for me) that this will change the location of your mongodb db files.

Fix insecure mongod startup recommendation

---

analysis/TBD/TBD.go
util/util.go

p.s. go doesn't have a min/max for ints in the standard library

Make sure beaconing runs on a single core

---

analysis/TBD/TBD.go
analysis/crossref/beaconing.go
analysis/crossref/crossref.go
analysis/crossref/scanning.go
analysis/scanning/scan.go
analysis/structure/hosts.go
analysis/structure/uconn.go
analysis/urls/url.go
analysis/useragent/useragent.go
commands/show-beacons.go
config/config.go
database/control.go
datatypes/TBD/TBD.go
datatypes/crossref/crossref.go
etc/rita.yaml

Aggregations were using .all to pull the results back into the client every time we aggregated. I changed the method to return an iterator. Additionally, I added cross reference analysis to the analysis modules. It is designed with an expansible selector framework. Scanning and beaconing selectors have been created.
WARNING!!!!! Unfortunately, this code is poorly tested. It compiles and looks correct, but I am not in a position to test the code.
This pull request serves to inform developers of code to come. The crossref analysis will be represented by two collections: internXREF and externXREF. The schema for records in these collections is string: name, string: host where name is the name of the analysis module in which this host was found.
Mongo does not enforce unique restraints on …

Added cross reference analysis for scanning and beaconing. Additionally fixed aggregations.

---

Readme.md
analysis/TBD/TBD.go
analysis/blacklisted/blacklisted.go
analysis/crossref/beaconing.go
analysis/crossref/blacklisted.go
analysis/crossref/crossref.go
analysis/crossref/scanning.go
analysis/scanning/scan.go
analysis/structure/hosts.go
analysis/structure/uconn.go
analysis/urls/url.go
analysis/useragent/useragent.go
commands/reset-analysis.go
commands/show-beacons.go
commands/show-blacklisted.go
config/config.go
database/control.go
datatypes/blacklisted/blacklisted.go
etc/rita.yaml
install.sh

- Add Ben LeBrun's additions to the installer.
- Fix installer for sudo ./install paradigm, removed netcat.
- Added uninstaller to the installer script.
- Moved user config to ~/.rita/config.yaml.
- Moved safebrowsing db to ~/.rita/safebrowsing
- Allow for use of environment variables in the RITA config (this is pretty neat!) 
- Blacklisted was adding the ip addresses from the hostnames table as well as hosts, this created duplicate entries
- Fixed a regression in show-beacons from the aggregation fix that came with crossref.
- Fixed a bug where reset-analysis would only reset a database if analysis had succeeded on that database.
- Rewrote the blacklisted output for pretty printing and for accurately finding the ip's of the computers that visited the blacklisted sites.
- Lowered default …

Bugfixes for staging branch

---

database/meta.go
parser/conn.go
parser/dns.go
parser/http.go
parser/parser.go
parser/parsertypes.go

Previously in the parser, we were parsing in bro's collections as strings which prevented us from performing analysis on DNS logs. Also the dns collection wasn't being properly built/ indexed. This addition has been tested on several (4+) datasets.
Note: this will be the start of a new dev branch on the ocmdev repo.

Added basic support for Bro's collection types

---

parser/parser.go

Fixes issue #40 
Stop error from percolating up, continue parsing, and check if field exists in struct at deserialize time.

Fix extra fields from breaking rita parser

---

analysis/dns/explodedDNS.go
commands/analyze.go
commands/commands.go
commands/show-beacons.go
commands/show-explodedDns.go
config/config.go
datatypes/data/data.go
datatypes/dns.go
datatypes/dns/dns.go
etc/rita.yaml
parser/parser.go

Implements the analysis described on issue #24. 
We blow apart a FQDN such as imap.google.com into three strings:
```
imap.google.com
google.com
com
```
For each of these strings we calculate how many times each one was looked up and how many unique subdomains exist for each domain (including 1 for the endpoint representing the string itself).
So, if I looked up imap.google.com x 2, calendar.google.com, yahoo.com, and calendar.yahoo.com, Rita would produce:
NOTE: visited is technically incorrect, it is an over estimate because if someone visits imap.google.com, they may not have visited google.com. However, it provides a decent heuristic. A new name should be developed. 
```
imap.google.com subdomains: 1 (itself) visited: 2
calendar.google.com subdomains: 1 (itself) visited: 1
google.com …
```

Exploded dns analysis

---

parser/http.go

The parser done broke when I added collection types earlier. Found out when going to parse a new set of logs.

Fix wrong type on tags field for http

---

analysis/beacon/beacon.go

An issue occurred when using Bowley skew with very low dispersion. If Q2 == Q1 or Q2 == Q3, bowley skew responds violently, returning a full 1 or -1. If the quartiles are that close, then we have a very, very large spike in the delta times which skews the histogram as whole, but should not be considered as the max possible skew. Rather, if we have that large of a spike in the delta time histograms, we should score the connection very high as a beacon.
This fixes an issue when testing against Powershell Empire.

Fix error in using bowley skew with very low dispersion

---

commands/delete-database.go
commands/reset-analysis.go

Add Confirmation for Reset-Analysis Fixes #84

---

commands/show-beacons.go

Fixes segfault in show-beacons #81

---

commands/reporting.go
reporting/report.go

Stop html-report segfault. Fixes #97

---

analysis/beacon/beacon.go
commands/analyze.go
commands/commands.go
commands/delete-database.go
commands/import.go
commands/reporting.go
commands/reset-analysis.go
commands/show-beacons.go
commands/show-blacklisted.go
commands/show-databases.go
commands/show-explodedDns.go
commands/show-long-connections.go
commands/show-scans.go
commands/show-urls.go
commands/show-user-agents.go

There isn't an open issue for this PR. However, while working on the new blacklist module, I became rather annoyed with rita's cli. I removed the all flag so it displays all results by default. I figure you can use `head` to limit the output. Then, I made sure the configuration file flag was actually being used on all of the commands. Finally, I fixed some errors that were being swallowed, and added some better error reporting. For instance if you issue a show command with an invalid database, it will respond with `No results were found for (database).`

Fix various cli bugs. Remove all flag.

---

database/resources.go

Group file logs into a directory based on time. Add logs for other log levels which were being dropped. Use path.Join to make all filesystems happy.
Fixes #104

Fix file logging. Fixes #104

---

analysis/structure/uconn.go
analysis/urls/url.go
parser/parsetypes/conn.go
parser/parsetypes/dns.go
parser/parsetypes/http.go

The indexes on the import collections were not being used, and some collections needed indexes that were not there. Standardized indexes on id_origin_h, id_resp_h across all logs. Added user_agent index to http such that the sources for user agents can be found.

Fix parse indexes

---

analysis/blacklist/blacklist.go
config/config.go
database/resources.go
etc/rita.yaml

Fixes #105 
In order to configure RITA to  authenticate to a MongoDB server over tls, set up your config like so:
MongoDB:
```
ConnectionString: mongodb://username:password@some.address:27017
AuthenticationMechanism: SCRAM-SHA-1
TLS:
Enable: true
CAFile: /path/to/my/private/certificate/authority
```
Of course the CAFile is not required if using a verified certificate.

Apply TLS to MongoDB Connection Fixes #105

---

parser/fsimporter.go

While parsing bro logs, I ran into an issue revolving around the current directory. RITA will parse the files in the current directory into the current day's database. Since this creates the database for the current day, when I go to parse the rest of the day's logs after they are archived, RITA fails.
A proposed solution: simply don't parse symlink'd directories.
(Perhaps this behaviour should be configurable?)

Prevent RITA from following symlink'd directories

---

parser/datastore.go
parser/fsimporter.go
parser/mongodatastore.go

Added more granular locking to parser, prevent panic when importing data into an already analyzed dataset.
Establishes base line behavior for issue #133

Prevent Parser from Panicking on Import Into Analyzed DB

---

analysis/structure/hosts.go
datatypes/structure/structure.go

Add ipv4, ipv4_binary, and ipv6_binary fields to the hosts table. IPv4 addresses are stored as 64 bit numbers since MongoDB uses signed integers only. IPv6 addresses are stored as objects with four 64 bit numbers each holding a 32 bit number representing a fourth of the address.

Added integer representations of the ip addresses in the hosts table

---

Dockerfile
config/config.go
config/static.go
database/mock.go
database/resources.go
etc/rita.yaml
etc/tables.yaml
install.sh

Split the table config out into its own file in hopes that that the table config will be more stable than the user config. This is a transition towards hard coding the table config into the RITA binary.
Also updated the installer. If you try to run the new installer you will get the following output:
The failure is due to table.yaml not being in master. The debconf errors are a result of running the script in docker without the apt-utils package installed.
However, if the file existed the following output would be displayed.
Fixes issue #103

Split config into two files, updated install script to be more interactive

---

Contributing.md
analysis/beacon/beacon_test.go
analysis/beacon/beacon_test_data.go

Changed because we changed the way we evaluate beacons, may need to find new tests to fill in the ones that we've changed
To run the tests in the Rita project folder type `test ./...`

Adding updated ranges for expected Beacon test results

---

Gopkg.lock
Makefile
commands/analyze.go
config/config.go
config/running.go
config/static.go
database/meta.go
parser/mongodatastore.go
rita.go

Added better support for semver in RITA. RITA now stores two version tags, one with the latest tag (latest semver version), and one with exact commit details (ExactVersion). Additionally, RITA will check for incompatibilities at parse time and import time. If RITA attempts to import data into an unanalyzed, incompatible database, it will log out an error (PS we should probably add a log hook for errors to get get printed to the console). Further more, if RITA attempts to analyze a dataset imported with an incompatible version of RITA, the software will warn the user, and skip the analysis.

Versioning Update

---

analysis/structure/hosts.go
analysis/structure/ip.go
commands/analyze.go
config/tables.go
datatypes/structure/structure.go
etc/rita.yaml
etc/tables.yaml

Note: this changes etc/rita.yaml, and as such will affect the split config PR.

Split integer representations of IP addresses into their own collections

---

Readme.md
commands/analyze.go
commands/commands.go
commands/delete-database.go
commands/import.go
commands/reporting.go
commands/reset-analysis.go
commands/show-beacons.go
commands/show-bl-hostname.go
commands/show-bl-ip.go
commands/show-bl-url.go
commands/show-explodedDns.go
commands/show-long-connections.go
commands/show-scans.go
commands/show-urls.go
commands/show-user-agents.go
config/running.go
config/static.go
database/meta.go
etc/rita.yaml
install.sh
parser/fileparsetypes/fileparsetypes.go
parser/fsimporter.go
parser/indexedfile.go

1.) Clean up the cli so you don't have to specify -d for commands which take a database as an argument
2.) Remove the Bro DirectoryMap (all import mapping is done on the cli)
3.) Change the -i and -d to positional arguments in import
4.) Add a --split option on import for splitting by subfolder and splitting by date
Splitting by subfolder appends the subfolder a bro log is found in to the root db name. This can be used with Bro's default file structure to import to DBNameBase-YYYY-MM-DD. Splitting by date tries to infer the dates when each connection is logged and appends that date to the resultant db. (i.e. the current UseDates option)

Add the ability to split logs into dbs by subfolder, clean up the cli

---

Dockerfile
Makefile
Readme.md
docs/Docker Usage.md

- Update go version for docker image
- Build out to a statically linked binary (linux 64-bit)
- Move documentation to docs folder
- s/CounterMeasures/Countermeasures

Extending docker capabilities and adding statically linked binary build

---

analysis/sanitization/sanitization.go
commands/analyze.go
commands/reset-analysis.go
parser/fileparser.go
parser/parsetypes/conn.go
parser/parsetypes/dns.go
parser/parsetypes/http.go
parser/parsetypes/parsetypes.go

Currently, http records are preprocessed as they are imported in order to clean up request uri's which are absolute urls. This cleaning is important in order to obtain accurate results in the long urls portion of analysis. However, this cleaning relies on go specific libraries. In order to support the bro-rita plugin as a drop in replacement for rita's parser, this logic must be moved to the analysis step. This PR adds a "sanitization" step to analysis, in which offending records are found and updated.
Additionally, this PR changes DNS.RTT's mongo tag to "rtt" from "RTT". This change matches Bro's name for the field. 
With this PR, bro-rita will become a viable drop in replacement for rita's existing parser.

Move Complex Logic from Import into Analysis [Supports bro-rita plugin]

---

docker-compose.yml
docs/Docker Usage.md

I also included the `docker-compose.yml` file that I didn't realize I had missed before.
Note that the references are for `quay.io/activecm/rita:master` which doesn't exist currently. As soon as dev is merged into master they will be valid.

Updating docker references to use Quay

---

Contributing.md
Readme.md
docs/Manual Installation.md
docs/Releases.md
install.sh

Changes installer.sh to pull a statically linked RITA binary for Linux x86-64 from github.com rather than installing go and building the rita binary.
Uses the github releases API to grab the latest release version.
Requires rita, config.yaml, and LICENSE to be present in every release here forward.

Pull a statically linked RITA binary from github

---

test-install.sh

This test script will run the installer on ubuntu 14.04, 16.04 and centos 7. If the installation process fails at any time, the test script will fail.

Added a test script for the installer

---

analysis/blacklist/urls.go

Throughout RITA, data size is determined using orig_ip_bytes/ resp_ip_bytes rather than orig_bytes/ resp_bytes. The prior are calculated at the IP packet level, while the latter are calculated at a protocol dependent level (TCP in the case of blacklisted urls). The changes were tested using the custom blacklist feature. Note: You will see an increase in the reported amount of data transported to and from blacklisted urls.

[Hotfix] Make the Blacklist Urls Module use orig_ip_bytes instead of orig_bytes

---

commands/reset-analysis.go

The `reset-analysis` prompt wrongly displayed Yes as the default action, and asked for input on the next line. It has been brought in line with `delete-database`.

Fix the prompt for reset analysis (to match delete-database)

---

analysis/beacon/beacon.go
analysis/crossref/crossref.go
analysis/dns/explodedDNS.go
analysis/dns/hostnames.go
analysis/scanning/scan.go
analysis/structure/hosts.go
analysis/structure/ip.go
analysis/structure/uconn.go
analysis/urls/url.go
analysis/useragent/useragent.go
database/db.go

`DisableIdIndex` is currently deprecated. We used it to speed up analysis since we don't make use of the index. However, the `_id` index is required from MongoDB 3.7.5 on. While 3.7.x onward is considered unstable, these changes are coming down the line in 3.8. This commit ensures future compatibility.

Remove DisableIdIndex as the option is deprecated and is an error in 3.7+

---

etc/rita.yaml

The amount of RAM used during import is given by the equation:
`# collections * # databases * size of log record * size of ImportBuffer`
Currently, importing 10 databases requires `3 * 10 * roughly 512 * 100000 bytes` or `1.43 GiB` of RAM. 
Setting the import buffer size to `30000` brings the the RAM needed to just under .5 GiB which is more reasonable. 
Ideally, we would allocate an import buffer and share it amongst all of the imported logs rather than use a buffer per collection. This would prevent the need for more RAM as more databases are imported. 
Alternatively, we can import one database at a time so there is a max of 3 buffers running around at any given time. However, this requires a larger patch to the import subsystem.

Lower the import buffer to safely import 10 datasets with .5 GiB RAM

---

database/db.go
docs/Manual Installation.md
resources/resources.go

Recently encountered a user running RITA with MongoDB 4.0.0-rc. Ensures the correct version of MongoDB is in use.

Check that MongoDB version is >= 3.2 and < 3.7

---

Gopkg.lock
analysis/beacon/analyzer.go
analysis/beacon/analyzer_test.go
analysis/beacon/beacon.go
analysis/beacon/collector.go
analysis/beacon/collector_test.go
analysis/beacon/collector_test_data.go
analysis/beacon/writer.go
analysis/beacon/writer_test.go
config/testing.go
datatypes/data/data.go

Issue #117 is a bug which creates a large amount of noise in the beaconing analysis. Failed TCP connections such as those generated by a TCP SYN scan appear with regularity in both time and data size. However, these connections never complete the TCP 3 way handshake. This prevents these connections from carrying meaningful data (outside the realm of abusing the protocol). When these connections are filtered from the beacon results, more important findings make their way to the top.
The patch was tested on [maccdc2012_00013.pcap](https://download.netresec.com/pcap/maccdc-2012/maccdc2012_00013.pcap.gz) which contains a large number of port scans. 
Additionally, the beacon tests were refactored and extended (particularly for the collector).

Filter unestablished tcp beacons fixes #117

---

install.sh

Hard code the version string in the rita installer and print it out when run.
1. Having an older installer install a newer version of RITA will eventually break. We can't always maintain the level of backwards/forwards compatibility to keep that up forever. 
2. It's much easier to troubleshoot bug reports if the installer is deterministic in time and prints out its own version number.

Hard code version number into installer

---

install.sh

When we moved from compiling rita locally to downloading it pre-compiled, we no longer need git or make as dependencies.

git and make are no longer required for the install

---

Makefile
install.sh
rita.go

Addresses #244
While the issue states that some commands should be renamed all of the reasoning given speaks to general usability issues that would be solved by tab completion.
If nothing else tab completion is nice.

Activate bash tab autocomplete

---

Gopkg.lock
commands/analyze.go
database/meta.go
database/meta_test.go
parser/mongodatastore.go

See PR #258. This PR follows up on the comment [here](https://github.com/activecm/rita/pull/258#issuecomment-428366524) by introducing the runDBInfoQuery method to ensure the data migration happens across all MetaDB database methods.

Alternative Migration: FIX #237 Allow Analysis While Importing Separate Data

---

install.sh

Testing:
Mongo 3.6 (new install):
Mongo 3.6 (upgrade):
Suggestion for testing:
1. Install RITA v1.0.3 or v1.1.0 on a system.
2. Verify that Mongo version 3.4 is installed: `mongod --version`
3. Update RITA using the installer in this pull request.
4. Verify that Mongo version 3.6 is installed: `mongod --version`

Update Mongo version to 3.6

---

docs/Manual Installation.md

Included references to installing Dep and broke each component out into individual sections for easier linking and readability.
Closes https://github.com/activecm/rita/issues/263

Updating manual install documentation

---

database/meta.go
parser/fsimporter.go

This change removes the `createMetaDB` function and related code. The rationale is discussed in the issue this closes.
Additionally, comments are added to a function whose name is easily confused with unrelated Mongo terminology.
Closes #286 
First, I started with a clean database by dropping MetaDatabase.
```
> db.dropDatabase()
{ "dropped" : "MetaDatabase", "ok" : 1 }
```
Next, I imported a sample dataset and verified that it was populated and MetaDatabase was created.
```
$ ./rita import sample-data/bro/dnscat dnscat
[+] Importing sample-data/bro/dnscat
[-] Finding files to parse
...
[-] Indexing log entries. This may take a while.
$ rita show-databases
dnscat
```
```
> show dbs
MetaDatabase  0.000GB
admin         0.000GB
config        0.000GB
dnscat        0.122GB
local …
```

Removing createMetaDB and adding docs to file indexing function

---

analysis/beacon/writer.go
analysis/blacklist/ips.go
analysis/structure/hosts.go
commands/analyze.go
datatypes/structure/structure.go

add fields to hosts

---

Gopkg.lock
Gopkg.toml
commands/test-config.go
commands/update-check.go
config/config.go
config/running.go
config/static.go
config/static_test.go
config/tables.go
config/testing.go

This pull request gives default values to every member of the config struct. This allows us to gracefully handle older /etc/rita/config.yaml files. If a section or value is missing we can just define a sane default, which is what most people's config files would contain anyway.  And a user can always override defaults with their config file.
This change allows us to add new fields without worrying about migrating a user's previous config file. These pull requests will immediately benefit from this change.
- https://github.com/activecm/rita/pull/311
- https://github.com/activecm/rita/pull/310
- https://github.com/activecm/rita/pull/328

Implement default config values

---

etc/rita.yaml

This PR adds and documents several networks to the default config file.  [RFC 5735, section 4](https://tools.ietf.org/html/rfc5735#section-4) was used as a reference.
I tested the config file was parsed correctly when uncommented.
```
./rita test-config
...
Filtering:
AlwaysInclude: []
NeverInclude:
- 0.0.0.0/32
- 127.0.0.0/8
- 169.254.0.0/16
- 224.0.0.0/4
- 255.255.255.255/32
InternalSubnets:
- 0.0.0.0/8
- 10.0.0.0/8
- 172.16.0.0/12
- 192.168.0.0/16
...
```

Adding more recommended default networks to Filtering section

---

etc/rita.yaml

The major change is enabling NeverInclude values by default. The values provided should be safe to use in the vast majority of networks.

Enabling NeverInclude values by default

---

commands/analyze.go
config/static.go
etc/rita.yaml

Adds Config options that allow user to not use modules during analysis.
It might be better if the modules themselves were in control of whether or not they run.
But then the logs would still be reporting on non-activated functions and resolving that problem seemed out of scope for this PR.
Closes #266

Fixes #266: Create config options for modules

---

parser/fsimporter.go

re-enabling writing out conns logs to mongo due to long conns module

re-enable writing to conns for long conns module

---

install.sh

Install ja3 module into Bro as part of the Rita installer.

---

pkg/certificate/mongodb.go

This PR fixes a bug that resulted in UserAgent Analysis appearing twice in the analysis output.
The invalid certificate analysis was writing an incorrect title out to the screen.
Before:
```
[-] Host Analysis:            4809 / 4809  [==================] 100 %
[-] Uconn Analysis:           16123 / 16123  [==================] 100 %
[-] Exploded DNS Analysis:    3683 / 3683  [==================] 100 %
[-] Hostname Analysis:        3683 / 3683  [==================] 100 %
[-] Beacon Analysis:          16123 / 16123  [==================] 100 %
[-] UserAgent Analysis:       16 / 16  [==================] 100 %
[-] UserAgent Analysis:       41 / 41  [==================] 100 %
```
After:
```
[-] Host Analysis:            4809 / 4809  [==================] 100 %
[-] Uconn Analysis:           16123 / …
```

Fix Invalid Certificate Output Text

---

Readme.md
commands/import.go
config/static.go
config/static_test.go
config/testing.go
etc/rita.yaml
parser/fileparser.go
parser/indexedfile.go

Closes #417 
Fixes `rita delete XXX` such that the files that were imported into `XXX` from subdirectories are actually removed. 
Removes the ability to import log files from subdirectories. 
Renames DBRoot to DBName since nothing will be appended to the value.

417 fix v3 db delete

---

Readme.md
docs/Docker Usage.md
docs/Mongo Configuration.md
docs/Upgrading.md

This PR is a first pass at addressing #441. 
This PR brings the main README.md up to date for v3, mainly focusing on the changes to the import process.
The README.md has been edited to reflect the absence of the analyze step and the addition of rolling datasets. 
In addition:
- references to Bro have been changed to Bro/Zeek in the main README
- `IntenalSubnets` typo has been fixed in the main README
- the "Examining Data" section has been updated to reflect the currently available `show-x` commands in the main README
- references to very old RITA configuration setups have been updated in the `docs/` folder
- a small blurb has been added to Upgrading.md regarding the v3 transition. We may want to rewrite Upgrading.md in its entirety.

Update Documentation for v3

---

install.sh

Closes #451 
Note, this still needs to be tested both on CentOS and Ubuntu.

Avoid downloading executable script to /tmp

---

config/static.go
config/static_test.go
config/testing.go
database/meta.go
etc/rita.yaml
resources/resources.go
resources/testing.go

I removed the `ImportBuffer` config item since it was not being used in the code.  This left only `MetaDB` under the `Bro` config section.  Since this didn't really seem to belong in this section anymore I moved `MetaDB` to the `MongoDB` section.
The `BroStaticCfg` struct in `config/static.go` is still being used to store the rolling analysis command line options so I didn't completely remove this. If we have a better place for these values, we could get rid of this struct too.
I built rita, imported a dataset, and confirmed that there were beacon results. Additionally, `make test` passes.  
Anyone using an old config file will revert to the default of "MetaDatabase" for the `MetaDB` field since they won't have this under the `MongoDB` section. This could cause anyone who changed their …

Removing Bro config section

---

pkg/certificate/mongodb.go
pkg/explodeddns/mongodb.go
pkg/hostname/mongodb.go
pkg/useragent/mongodb.go

Some of the keys for index files (particularly the Useragent keys) were causing overflow to the max key length. This is caused by the max index key size being 1024 bytes.
This PR checks the key length in the Upsert function in various analyzers to ensure we don't overstep that 1024 limiter.
Closes: #449

449-useragent-overflow

---

parser/fsimporter.go

This adds a warning to the import of a database. If the user runs import currently it will just move past UCONN and Host data and keep evaluating. If the user has their config improperly configured then tracking that issue down could be tricky. This adds a couple lines that says the UCONN data is empty and they should double check their config file (since it seems weird that someone would run data with no local traffic)

Empty UCONN Warning

---

commands/show-bl-ip.go

Fixes small bug with limit flag missing on one command. Fixes #486

Add limit flags to show-bl-dest-ips

---

Readme.md

Update the link to documentation about Security Onion with RITA to point to the new version of Security Onion's wiki.

Update Security Onion link in documentation

---

pkg/host/analyzer.go
pkg/uconn/analyzer.go

If InternalSubnets is changed and new data is imported into a rolling database, any existing hosts (IPs) in the database wouldn't be updated based on the new value of InternalSubnets. For instance, if you had an IP of "22.22.22.22" that was not included in the InternalSubnets it would be marked as `{local: false}` in the host database entry. If you added this IP to your InternalSubnets you'd expect it to then have `{local: true}`. However, since the entry already existed it wouldn't be updated. 
This pull request makes this change, along with several other fields that could be affected in the same way.

Fix for if InternalSubnets is updated

---

Makefile

If you try to use a `rita` binary that is built using `go build` without the proper version flags rita will fail to run with this message:
```
./rita  -version
rita version undefined
[!] Version error: please ensure that you cloned the git repo and are using make to build.
[!] See the following resources for further information:
[>] https://github.com/activecm/rita/blob/master/Contributing.md#common-issues
[>] https://github.com/activecm/rita/blob/master/docs/Manual%20Installation.md
Failed to config: Invalid character(s) found in major number "undefined"
```
If you try to fix this problem by them running `make`, make will not rebuild the rita binary because the binary's create/modify time are newer than any of its dependencies. This can lead to confusion.
This pull request makes the …

Force rita to be rebuilt

---

install.sh

Only small changes here.
Added a conditional in the function `__gather_OS()` to add a new variable, `_MONGO_OS_CODENAME`. I then changed the `__install_mongodb()` function's reference from `$(lsb_release -cs)` to `${_MONGO_OS_CODENAME}`.
Hopefully this all looks good!
Thanks.

Add install.sh support for Ubuntu 18.04

---

commands/commands.go
commands/delete-database.go
commands/import.go
commands/import_test.go
config/static.go
database/meta.go
parser/fileparsetypes/fileparsetypes.go
parser/fsimporter.go
parser/indexedfile.go

This PR introduces the `--delete` flag to the `rita import` command. This flag deletes any existing data in the target import location before importing new data.
If the target database is not a rolling database, the flag is used as:
```
rita import --delete /path/to/file_or_dir_1 [/path/to/file_or_dir_n ...] target_database
```
If the target database is a rolling database, the CID for the chunk to be replaced ~must~ may be specified:
```
rita import --delete -CC N /path/to/file_or_dir_1 [/path/to/file_or_dir_n ...] target_database
```
If the CID is not specified and the target database is a rolling database, the latest chunk is replaced:
```
rita import --delete --rolling /path/to/file_or_dir_1 [/path/to/file_or_dir_n ...] target_database
```
The command will fail on existing rolling …

Allow Users to Re-Import Logs

---

pkg/uconn/analyzer.go

Fixed maxdur to include incoming connections

---

install.sh

On November 15, 2019, the JA3 installation routine broke in the RITA install script. As part of the bro -> zeek rebrand, salesforce changed their bro scripts to zeek scripts. This broke the download urls in the install script. The install fails silently, leaving the message `404: Not Found` in each of the downloaded files. 
Running bro with broken files and the local policy results in the following error:
```
error in /opt/bro/share/bro/site/./ja3/__load__.bro, line 1: syntax error, at or near ":"
```
The following files are affected:
- `/opt/bro/share/bro/site/ja3/__load__.bro`
- `/opt/bro/share/bro/site/ja3/intel_ja3.bro`
- `/opt/bro/share/bro/site/ja3/ja3.bro`
- `/opt/bro/share/bro/site/ja3/ja3s.bro`
I've pinned the download links to the pre-rename commit in this PR. Future work should …

Fix JA3 Installation

---

install.sh

From a support request, recognize "RedHatEnterprise" as a valid OS label.

Add identifier so we support RHEL workstation as well as RHEL server

---

install.sh

Adds a catch and warning for when the user has a Bro package installed that does not contain its files in `/opt/bro`. If the user has a Bro package installed that the install script does not recognize, the script disables the Bro installation routine and displays a message to the user.
This warning will show itself if the user has installed the default Bro package on Ubuntu 16 or 18.
Currently, if a user installs RITA alongside the default Bro packages from the Ubuntu repositories, they will receive a message like the following:
```
[-] Bro IDS is already installed
grep: /opt/bro/bin/../share/bro/site//local.bro: No such file or directory
If you need to check or change your network interfaces, please do so now
by switching to a different terminal and making any changes.  Please note
that …
```

Prevent Installation Errors When Default Ubuntu Bro Package Is Installed

---

Contributing.md
docs/Manual Installation.md

Correct _Gittiquette Summary_ note in Contributing.md; repoint repo to fork using `git remote set-url`, not `git remote add`.
```
docs (master) $ git remote set-url origin https://github.com/joswr1ght/rita
docs (master) $ git push
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 4 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 433 bytes | 433.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/joswr1ght/rita
ece0923..44d2ee0  master -> master
```

Gittiquete summary fix

---

commands/show-explodedDns.go

Wrap long domain names in human readable table view for show-exploded-dns.
This PR is a hack, shared to support a feature request. The human readable output of RITA is very difficult to parse on terminals where width is less than the total table size. I've changed the max domain name length per line to an arbitrary 80 characters, wrapping longer values to a new line. This change also requires the addition of a row separator line, to avoid confusion where a wrapped line could appear as a new record.
If there's a better way to represent or implement this, I'm all ears!

Terminal width human reporting (for exploded dns)

---

install.sh

removed line in code that was initially used to fix #189 because we've been able to manually install Bro on CentOS without that workaround (see #278)

Removed workaround for bro install on CentOS

---

commands/show-long-connections.go

Change the duration value in `show-long-connections` to a human-readable duration.
This change introduces human readable duration to the output of `show-long-connections`. The old display was a number of seconds, which were sometimes represented as an exponential value, which is kind of hard for most users to parse easily. This change modified the duration to display time in a readable format. See attached screenshots.

Human readable duration for show-long-connections output

---

parser/fsimporter.go

Addresses the issue mentioned in issue #538 by setting it so an empty user agent string will be saved as "Empty user agent string" and an empty JA3 hash is saved as "No JA3 hash generated"

Fixed issue with empty user agent string and empty JA3 hash

---

parser/fsimporter.go

Fixed the spelling of RITA in the buildUconns and buildHosts functions in fsimporter.go
Closes #550

Fixed spelling in fsimporter

---

install.sh

Bro 2.6 will not compile under Ubuntu Xenial in the OpenSuse Build Service. This breaks the bro installation on Xenial. I've copied the build files for Bro 2.6 and edited them to build Bro 2.5.5 for Xenial in OBS. 
~I have the script download the debs and install them manually so this one off repo isn't installed into RITA users' machines. This prevents the need to migrate users' repo configs once RITA migrates to using Zeek.~
This PR changes the installer to use ACM managed repos for both Bro 2.6 and Bro 2.5.5.
I've also removed a couple usages of sudo that were unnecessary since the script requires super user permissions up front. These sudo calls broke the script while I was testing in docker.

Install bro 2.5.5 for ubuntu xenial; Use ACM managed repos

---

Readme.md

Update bro/zeek links in Readme.md: Zeek website has been update and the current links result in 404 error.

Update bro/zeek links in Readme.md

---

parser/fsimporter.go

This PR attempts to put a cap on the amount of RAM needed to run RITA. It does so by batching up imports and importing each batch into the same chunk. 
The new code batches the input files by gathers N files of every type such that each 
batch doesn't exceed 2 GB in file size and imports each batch into the same chunk.
It does this by first sorting the input files by path and then grouping them by file type (conn/ http/ ssl/ etc). Next, it greedily takes the next available file from each file type group. If adding the next set of files would make the current batch too large, it splits off the current batch and starts a new one.
This PR relies on zeekctl to create the bro files properly and rotate them at a regular interval for the best experience. If there is not an even number of files …

Batch Files During Import To Lower RAM Usage

---

parser/indexedfile.go

The change made in https://github.com/activecm/rita/pull/555 introduced a new error message that is printed on every incompatible log file encountered. https://github.com/activecm/rita/pull/555/files#diff-db535b165427291263a2f98e046f30e0R158
However, there is no newline at the end of that message which makes all the errors run together if there are more than one. For example:
```
[!] An error occured while indexing ignore/empire-ssh/capture_loss.05:00:00-06:00:00.log. Perhaps this log is empty?	[!] An error occured while indexing ignore/empire-ssh/capture_loss.02:00:00-03:00:00.log. Perhaps this log is empty?	[!] An error occured while indexing ignore/empire-ssh/capture_loss.11:00:00-12:00:00.log. Perhaps this log is empty?	[!] An error occured while indexing …
```

Remove error printed on every incompatible file

---

Readme.md

A % in a cron entry will be replaced with a newline and the remainder of the command will be fed as stdin.  To avoid this, all %'s in a crontab must be escaped with a backslash.

Escape % symbols in cron

---

Readme.md
commands/commands.go
commands/show-beacons.go
commands/show-bl-hostname.go
commands/show-bl-ip.go
commands/show-explodedDns.go
commands/show-long-connections.go
commands/show-strobes.go
commands/show-user-agents.go

Each of the `show` commands now supports a `-d` option that allows the user to specify a delimiter for the command's output. A couple of examples:
- `rita show-beacons -d ~ dataset_name` - Delimits the output by `~` instead of by `,`.
- `rita show-beacons -d "@@@" dataset_name` - Delimits the output by `@@@` instead of by `,`.
Under the hood, each `show` command's file now uses `fmt` to output instead of `encoding/csv`, and each output function now takes an additional `string` argument representing the delimiter. _This is still a comma by default._
The main `Readme.md` has been slightly updated to reflect this new functionality.
Closes #572

Specify Output Delimiter

---

parser/fsimporter.go

Closes #607
Removed the connection filter for only the dns entries so that those host ip's can get added to the hosts table.
[dns-test (1).tar.gz](https://github.com/activecm/rita/files/5974284/dns-test.1.tar.gz)
For this dataset that previously would not import the host creating the dns queries, rita now imports said host.

Remove connection filter for dns entries

---

parser/fsimporter.go
pkg/host/analyzer.go
pkg/host/mongodb.go
pkg/host/repository.go

- Changed the txt_query_count field to max_dns_query_count
- max_dns_query_count represents the dns query count for the domain that had the most dns queries made to it by its respective host
- Added a check to only add the host to the host map & increment dns query count if the domain isn't an empty string and doesn't end in in-addr.arpa, since it can create an inaccurate dns query count
- Removed the check for txt queries, making the src ip get added to the host map & incrementing the query count regardless of query type.
For [this dataset](https://github.com/activecm/rita/files/6025257/dns-test.tar.gz), 172.31.26.157 made 
- 2074 queries to *.honestimnotevil.com
- 3 queries to *.aitai.ne.jp
Since *.honestimnotevil.com had the most amount of queries made to it, 2074 makes it into the …

Change TXT query count to max DNS query count

---

pkg/host/analyzer.go

Fixes #612.
In the `show-exploded-dns` output, we display two values `Times Looked Up` and `Unique Subdomains`. 
Currently the host based exploded dns analysis i.e. `host.max_dns.count` is written to compute the number of times a host looked up the subdomains of a given (super)domain (`host.max_dns.query`). This is akin to the `Times Looked Up` field in the dataset wide exploded dns analysis.
This PR changes `host.max_dns.count` to compute the number of unique subdomains a host looked up for a given (super)domain. This makes the values match the `Unique Subdomains` values reported by `show-exploded-dns`.

Count the number of unique subdomains a host looked up for a given (super)domain rather than total number of queries

---

install.sh

We must edit the target version in the installer before creating a release as per docs/Releases.md.

set rita version to v4.1.0 in installer

---

config/static.go
etc/rita.yaml
parser/filter.go
parser/filter_test.go
parser/fsimporter.go
pkg/beaconfqdn/dissector.go
rita.go
util/ip.go

fixed a bug with threshold count for fqdn beacons and added always include and never include functionality for domain filtering

Domain filtering and fqdn threshold hotfix

---

pkg/remover/mongodb.go

FQDN beacons table wasn't added to the removal process for outdated chunks, leading to outdated results.

Fqdn chunk hotfix

---

commands/commands.go
commands/reporting.go
reporting/report.go

`--no-browser` / `-nb` boolean flag is added to `html-report` subcommand which allows users to prevent auto-launching the default browser.
Closes #593

add flag to prevent auto-launching of browser when generating HTML reports

---

commands/commands.go
commands/delete-database.go
commands/import.go
commands/reporting.go
commands/show-beacons-fqdn.go
commands/show-beacons.go
commands/show-bl-hostname.go
commands/show-bl-ip.go
commands/show-databases.go
commands/show-explodedDns.go
commands/show-long-connections.go
commands/show-strobes.go
commands/show-user-agents.go
commands/test-config.go
commands/update-check.go
rita.go

This PR does the following:
* makes `--config` a global option on the `rita` command.
* removes `--config` flag from subcommands (`import`, `html-report` etc.)
* uses [`GlobalString`](https://github.com/urfave/cli/blob/v1.22.0/flag_generated.go#L709) to fetch config value from global state. For reference, see this [issue](https://github.com/urfave/cli/issues/716).
Closes #595

make `--config` a global option on `rita` command

---

reporting/report-beacons.go
reporting/report-beaconsfqdn.go

Hi 
I've fixed a minor error in the html-export command.
This made the data very hard to parse with other tools, for instance pandas.
I've fixed it by adding the required `</td>` in the code after `.Ds.ModeCount`

Fixed missing </td> in report-beacons.go and report-beaconsfqdn.go

---

docs/Docker Usage.md

VERSION rather than RITA_VERSION is what is actually used by the docker compose file

Fixed typo in docker compose documentation

---

database/db.go
install.sh

This PR is to update to Mongo version 4.2.
It will check if the user currently has Mongo installed. If so, it will check if it is less than version 4.0. If so, it will first upgrade to 4.0 and then upgrade to 4.2.  It will set the feature compatibility in Mongo to 4.0 after upgrading to 4.0 but before upgrading to 4.2.
If 4.0 is already installed, it will upgrade directly to 4.2.
If no Mongo version is installed, it will cleanly install 4.2.
The user will be prompted before upgrading from a prior version of Mongo and will be encouraged to create a backup of their data before proceeding.
Closes #651

Update Mongo Version to 4.2

---

Makefile
Readme.md
docs/Docker Usage.md
docs/Manual Installation.md
docs/System Requirements.md

Update references from Mongo 3.6 to 4.2

---

config/static.go
config/static_test.go
etc/rita.yaml
parser/filter.go
parser/filter_test.go
parser/fsimporter.go

Removes the need for a user to specify their proxy servers for the beacons proxy module. Now, all http.log entries with the CONNECT method will automatically be considered for processing for the beacons proxy module. Entries will also be ignored if the Src IP or FQDN have been specified for filtering.
This also ensure that entries are not filtered if they are an internal->internal connection
Closes #664

Remove Need for Users to Specify Proxy Servers, Fix Filter Bugs

---

reporting/report-beacons.go
reporting/report-beaconsfqdn.go
reporting/report-beaconsproxy.go
reporting/report-bl-dest-ips.go
reporting/report-bl-hostnames.go
reporting/report-bl-source-ips.go
reporting/report-explodedDns.go
reporting/report-long-connections.go
reporting/report-strobes.go
reporting/report-useragents.go
reporting/report.go
reporting/templates/templates.go

This adds a date/time block to the top bar of the HTML report representing the `maxTime` of the generated logs. The timestamp is visible from all panels in the HTML report.
Closes #594

Add timestamp to HTML report templates

---

pkg/beaconfqdn/mongodb.go

Fixes #688
Adds the necessary unique indexes to cover the upserts performed in the fqdn and proxy beacon analyses. 
Running a `.explain` for the FQDN beacon selector (see #688) now returns the following plan without a filter stage:

Add unique indexes to `beaconFQDN` and `beaconProxy` collections

---

parser/files/reading.go

Fixes #694. 
In this PR, we ensure that RITA does not attempt to read the end of a log entry if we've already parsed the needed number of fields.

Fix skipping final field in log when the number of log fields does not match the number of fields in the header

---

config/static.go
etc/rita.yaml

Fixes #696
Assuming the parsed in dataset represents a day, this drops the strobe limit to 1 connection per second. 
If any pair of hosts is connecting one per second, we want to bring this to the user's attention regardless of the beacon score. Additionally, this prevents RITA from running the beacon analysis modules on very large lists of connections.

Drop stobe limit down to 86400 

---

parser/http.go

Fixes the filter for proxy entries when parsing the http.log file. The filter will no longer remove internal->internal cases when the entry is a proxy connection.

Fix http.log Filter for Proxy Entries

---

Readme.md
install.sh

Mongodb does not have a release file for Debian 11 (bullseye). This has been tested with no issues.
The Zeek installation binary comes from The OpenSUSE Project. This is an established and trusted project.
This has been tested on VMs with fresh installs of Debian 10/11 with no issues noted.
David Quartarolo is an ACM contractor and can be contacted via Slack if there are any questions.

Add Debian Install to install.sh 

---

Readme.md
install.sh

Following the discussion in #587, this PR instructs the installer to use the Ubuntu 18 MongoDB 4.2 package when installing on Ubuntu 20. I have tested this out on Ubuntu 20 and was able to successfully install RITA.

Support Ubuntu 20.04 LTS

---

parser/fsimporter.go

- since zeek records connections when they close, some connections that started before the ingested observation period can skew the ts range. We need to cap observation period to the last 24 hours for accurate beaconing analysis.

Patch to limit dataset timestamp range to 24 hours

---

parser/conn.go
parser/http.go
parser/ssl.go
pkg/beacon/analyzer.go
pkg/beacon/dissector.go
pkg/beacon/sorter.go
pkg/beaconfqdn/analyzer.go
pkg/beaconfqdn/dissector.go
pkg/beaconfqdn/repository.go
pkg/beaconfqdn/sorter.go
pkg/beaconproxy/analyzer.go
pkg/beaconproxy/dissector.go
pkg/beaconproxy/sorter.go
pkg/beaconsni/analyzer.go
pkg/beaconsni/dissector.go
pkg/beaconsni/repository.go
pkg/beaconsni/sorter.go
pkg/sniconn/analyzer.go
pkg/sniconn/repository.go
pkg/uconn/repository.go
pkg/uconnproxy/repository.go

This is a patch to store every timestamp in the uconn ts list rather than a unique set. This will not impact any of the scoring algorithms, which already gather the timestamps with `$addToSet`

Patch to fix uconn timestamp storage 

---

pkg/beacon/analyzer.go

Added a check when calculating `dsMadmScore` to set it to `0` if it is less than zero or `NaN`. 
During my troubleshooting, I noted that only `dsScore` had instances of `NaN`.  It looks like the other score parameters have checks for dividing by zero.
Tested and confirmed that previously `NaN` scored beacons now have real scores.

Fixed some beacon scores from being NaN

---

config/static.go
etc/rita.yaml

This PR enables the filter which drops external to internal traffic by default. This can be turned off by changing the `FilterExternalToInternal` field in the RITA config file back to false.
To test the changes, I  commented out the `FilterExternalToInternal` field in my RITA config and ran `rita test-config`. The filter was then enabled by default.

Filter external to internal traffic by default

---

pkg/beaconfqdn/mongodb.go

This PR lowers the bulk lookup limit in the beaconFQDN queries which map IP addresses in the parse set to domain names in the hostname collection. It is currently set to 200,000 lookups. The limit was put in place to prevent hitting the 16MB MongoDB  document ceiling while maximizing performance. However, the limit was set too high, and RITA ends up hitting the ceiling anyways in some cases. As a result, the beaconFQDN analysis may crash. 
The previous limit incorrectly estimated the size of the Unique IP lookup BSON documents. In order to get a better estimate, I wrote a separate piece of code to generate, serialize, and measure the length of the longest possible IPv4 and IPv6 lookups. After obtaining the new estimates, I came up with a new value for the threshold. The new limit is set …

Fix beaconFQDN crash when analyzing large amounts of data

---

parser/http.go

This PR adds a filter to the parser which filters out HTTP proxy connection entries if the source, proxy, and destination are all internal IP addresses. 
I tested this by adding the following entry to an http.log file and ensuring that the new code filtered out the resulting document int he `proxyUconn` collection.
```
1610645063.451000       CapEgukOzsRcJpPde       192.168.0.15    34705   10.10.10.10     1080    1       CONNECT 10.20.20.20     10.20.20.20:443 -       -       Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0   0       0       -       -       -       -       (empty) -       -       PROXY-CONNECTION -> keep-alive  -       -       -       -       -       -
```

Filter out proxy traffic which occurs over the internal network

---

commands/clean.go
commands/delete-database.go

Users cannot remove broken RITA datasets if the MetaDatabase goes out of sync with the list of databases in MongoDB. This should not happen unless there is a serious bug or crash. Nonetheless, it has happened in the past. 
This PR adds the clean command which searches for RITA datasets without MetaDB records and offers to remove them from the database, freeing up disk space without resorting to MongoDB administration tools.

Add rita clean command to remove RITA datasets without MetaDB entries

---

commands/clean.go

If the `scale` field appears before `dbStats` when asking MongoDB the size of a collection, the command will fail. The RITA clean command stores this query document using `bson.M` which does not guarantee the order of the fields. As a result, the command will fail at random. This PR ensures that RITA uses `bson.D` to store this query document. This preserves the order of the fields each time the code is executed.
Fixes #770 
Example mongo shell output:
```
> db.getSiblingDB("testdb-2022-11-21").runCommand({ "scale": 1024 * 1024, "dbStats": 1})
{
"ok" : 0,
"errmsg" : "no such command: 'scale'",
"code" : 59,
"codeName" : "CommandNotFound"
}
> db.getSiblingDB("testdb-2022-11-21").runCommand({"dbStats": 1, "scale": 1024 * 1024})
{
"db" : "testdb-2022-11-21",
"collections" : 11,
"views" : 0, …
```

Fix RITA clean 'no such command "scale"' error

---

parser/fsimporter.go
pkg/useragent/mongodb.go
pkg/useragent/repository.go
pkg/useragent/summarizer.go

If the number of useragents (including JA3 hashes and HTTP useragents) outnumbers the number of internal hosts, the existing useragent aggregation implementation runs slowly. 
This PR rewrites the useragent aggregation to:
- loop over each internal host in the current import session:
- search the `useragent` collection for the useragents associated with the host in this import session which are associated with less than 5 originating IP addresses over the past 24 hours 
- pull down the existing rare signatures associated with the host from the `host` collection
- loop over the new rare signatures:
- determine if each new rare signature matches an existing rare signature or not
- create an array of bulk updates for the `host` collection responsible for updating each existing rare signature …

Improve useragent aggregation runtime for datasets with many useragents

---

parser/dns.go
parser/ssl.go

- The SSL log filter did not check the FQDN in each entry against the always and never include lists in the filter. This has been fixed. SNI beacons and JA3 hashes can now be excluded by hostname.
- The DNS log filter did not filter out internal -> internal traffic or external -> internal traffic. This was originally implemented to ensure that traffic to internal DNS resolvers was analyzed. However, this was implemented before we had the always include list. This PR ensures that the DNS log filter matches the associated Conn log filter on the IP level. When deploying RITA, any internal DNS resolvers should always be added to the IP always include list.

Fix SSL and DNS log filtering

---

parser/conn.go
parser/dns.go
parser/fsimporter.go
parser/http.go
parser/open_conn.go
parser/ssl.go

This PR adds some checks in the log ingestion process. The checks validate that the bare minimum fields required for processing into a collection are present in a log entry before attempting to further parse that long entry for that collection. This was prompted by some malformed/incomplete ip addresses causing RITA to crash.

Parsed log field validation

---

config/static.go
config/static_test.go
config/testing.go
etc/rita.yaml
pkg/beacon/analyzer.go
pkg/beaconproxy/analyzer.go
pkg/beaconsni/analyzer.go

The connection count portion of TS Score portion of beacon scoring is artificially inflating the TS score. Originally, the connection count score was meant to reward beacons going off very frequently, with a perfect score being given to beacons that went off every 10 min or less. Since that led to both malware detection failure and false positives, the formula was adjusted to reward beacons that went off at least once per hour. However, the default thresholds in RITA for the beacon modules are already attempting to weed out analyzing host pairs that don't have at least 20 connections.  Since we want the lat least once per hour in a dataset and gave perfect connection count scores to hosts that had at least 24 connections, this score ended up being redundant and inflated the TS Score …

Removal of connection count portion of beacon scoring and adjustment of skew

---

parser/dns.go
parser/filter.go

This PR creates a new function `filterDNSPair` which is a copy of `filterConnPair` without the internal -> internal traffic filter and changes the DNS parser to use this new function. DNS is treated specially since we need to capture internal -> internal DNS traffic in order to detect C2 over DNS with an internal resolver. 
Currently, the master branch requires users to add their DNS resolver to the AlwaysInclude section of the RITA config file due to the changes in https://github.com/activecm/rita/pull/788. This was not previously required. Additionally, as it stands, there is no way to filter out external -> internal DNS traffic while keeping internal -> internal DNS traffic. 
With this change, users will be able to filter out external -> external and external -> internal DNS traffic. …

Don't filter internal -> internal DNS traffic

---

pkg/beacon/summarizer.go
pkg/beaconproxy/summarizer.go
pkg/beaconsni/summarizer.go
pkg/uconn/summarizer.go

This PR changes the summarize / aggregation phase of the IP beacons, proxy beacons, SNI beacons, and unique connection analyses to perform a total roll-up of the currently imported data for each host rather than a roll-up for the data that was just imported. This allows us to store a single copy of the roll-ups in the host collection for each internal host instead of a record per chunked import. In turn, we no longer have to worry about old roll-ups falling out of sync with new data. Closes #800
Testing:
I've tested this PR against the logs linked in #800 and ensured that the problem is fixed there. I am currently testing to ensure that we don't have any regressions on other datasets.

Only maintain one cid's worth of max scores in the host collection

---

docs/Manual Installation.md

This PR adds a third step to `Manual Installation.md`'s **Configuring the system** section, prompting the user to use `chmod 777`. Without that, following the instructions resulted in a permissions error.
closes #805 
Docs update
- Checked markdown preview to make sure it didn't look weird

Add step to manual install instrucions to run chmod 777

---

commands/show-dns-fqdn-ips.go
commands/show-ip-dns-fqdns.go
pkg/hostname/repository.go
pkg/hostname/results.go

This adds a new command, `show-ip-dns-fqdns <database> <ip address>` which shows the domain names that the IP address was resolved from.
closes #811
__Acquire FQDN(s) to compare RITA command against__
Navigate inside the directory of your zeek logs
Run `zcat dns.* | nice zcutter.py query answers -C` to view a list of FQDNs and IP addresses. Select an IP address to test against.
Run `zcat dns.* | nice zcutter.py query answers -C | grep <regex>| cut -d$'\t' -f1 | sort -u`, replacing <regex> with a regular expression to filter out just the FQDNs associated with the IP address. Here is a regex pattern for an IPv4 address you can use: `'^.*\t.*52\.9\.92\.15.*$'` just replace the digits with the digits of your IPv4 address.
These FQDNs are what you will be checking for when you run the command …

811 show ip dns fqdns

---

Dockerfile
docker-compose.yml
docs/Docker Usage.md
etc/rita_docker.yaml

Resolves bug preventing running RITA with Docker Compose. Created a ready-to-go configuration file for Docker named `rita_docker.yaml`, which is just a copy of `rita.yaml` but with "localhost" replaced with "db" in `ConnectionString`. Removed "links" key from rita service in `docker-compose.yml` since it is no longer needed. Pointed the Dockerfile to `rita_docker.yaml` instead of `rita.yaml`.
The usage guide was updated to new `docker compose` syntax and to assume user is not in the docker group and needs to use `sudo`.
closes #730 
Pull down RITA image
```
sudo docker pull quay.io/activecm/rita
```
Setup your variables (default config path is `./etc/rita_docker.yaml`)
```
export CONFIG=/path/to/your/rita/config.yaml
export LOGS=/path/to/your/zeek/logs
```
Test the configuration
```
sudo …
```

730 update docker resources

---

install.sh

It does not appear we use the saved certificates created by this (no longer available) script.

Disable extract-certs-pem.zeek
