activecm/rita

Readme.md
Did a test run of installing mongo using the tutorial on a system I'm testing this on, used more direct instructions than general instructions for users looking to simply copy and paste the commands.
=> Fixed some steps in the tutorial for better reader usability

Readme.md
=> Fix minor typo

analysis/blacklisted/blacklisted.go, commands/commands.go, commands/import.go, commands/show-beacons.go, commands/show-blacklisted.go, commands/show-scans.go, config/config.go, database/meta.go, etc/rita.yaml, parser/conn.go, parser/dns.go, parser/docwriter.go, parser/http.go, parser/parser.go, parser/watch.go, rita.go
- GOMAXPROCS on all operations
- Fix human readable flag in commands (was using global var)
- Removed unused padding funcs in commands
- Added control of thread creation for parser
- Majorly refactored the Watcher -> Parser -> Writer system
- Removed Thread config in bro config section
- Added support for deleting date based databases
- MetaDB was not being updated correctly
- Better support for detecting re-parses
- Better output on parse
=> Fix imporing bug https://github.com/ocmdev/rita/issues/27

Readme.md
The live readme can be found at [https://github.com/Zalgo2462/rita/tree/readme](https://github.com/Zalgo2462/rita/tree/readme)
=> Readme Update

analysis/beacon/beacon.go, analysis/blacklisted/blacklisted.go, analysis/crossref/blacklisted.go, analysis/crossref/crossref.go, analysis/dns/explodedDNS.go, analysis/dns/hostnames.go, analysis/scanning/scan.go, analysis/structure/hosts.go, analysis/structure/uconn.go, analysis/urls/url.go, analysis/useragent/useragent.go, commands/analyze.go, config/config.go, datatypes/dns/dns.go, etc/rita.yaml
Fixes #58. Also, fixed up some linter warnings. NOTE: this does change the config file
=> Fix pulling hostname->ip mappings from http Fixes #58

analysis/useragent/useragent.go, commands/show-user-agents.go, datatypes/useragent/useragent.go
This does not implement the data size aggregation, but we can open another issue for that.
Fixes #7
=> Fix user agent analysis and output Fixes #7

analysis/dns/explodedDNS.go, analysis/urls/url.go, analysis/useragent/useragent.go, commands/reset-analysis.go, commands/show-explodedDns.go, config/config.go, database/logcollections.go
=> Config cleanup, Remove GNUNetcat Fixes #59

Readme.md, install.sh
Fixes issue #42. Also enables installation on ubuntu 14-16.
=> Installer fixes for security onion fixes #42

analysis/urls/url.go, commands/show-urls.go, datatypes/urls/urls.go
The code can now output the most visited and longest urls in the http logs.
Fixes issue #7
=> Urls output Fixes #7

commands/commands.go, commands/reporting.go, commands/reset-analysis.go, commands/show-blacklisted.go, commands/show-explodedDns.go, commands/show-long-connections.go, commands/show-scans.go, commands/show-urls.go, commands/show-user-agents.go, commands/testconfig.go, reporting/report-beacons.go, reporting/report-blacklisted.go, reporting/report-explodedDns.go, reporting/report-long-connections.go, reporting/report-scans.go, reporting/report-urls.go, reporting/report-useragents.go, reporting/report.go, reporting/templates/csstempl.go, reporting/templates/templates.go
This merge requests takes care of the bugs and todos listed in the dev->master pull request #76
=> Dev Merge Fixes

analysis/beacon/beacon.go, analysis/beacon/beacon_test.go, analysis/blacklisted/blacklisted.go, database/control.go, database/meta.go, database/resources.go, parser/fileparser.go, parser/fsimporter.go, parser/indexedfile.go, parser/mongodatastore.go
See 
[Issue on logrus](https://github.com/sirupsen/logrus/issues/451)
[PR on mongo log hook](https://github.com/weekface/mgorus/pull/8)
=> Fix sirupsen logrus naming conflict

etc/rita.yaml
Forgot to clean this up earlier.
=> Remove White Listing Config Sections

parser/parsetypes/conn.go
Addressing issue #50 
While this might not fix the issue entirely, it will help.
=> Add ts to conn Indexes

analysis/beacon/beacon.go, analysis/blacklisted/blacklisted.go, analysis/crossref/beaconing.go, analysis/crossref/blacklisted.go, analysis/crossref/scanning.go, commands/analyze.go, commands/import.go, commands/show-blacklisted.go, commands/test-config.go, config/config.go, database/control.go, database/meta.go, database/mock.go, database/resources.go, datatypes/blacklisted/blacklisted.go, etc/rita.yaml, parser/fileparser.go, parser/fsimporter.go, util/util.go
Added options to enable/disable file logging and logging to the database. Made sure log hooks were enabled at all times. Fixed some linting issues.
=> Logging Fix Fixes Issues #85, #90

analysis/beacon/beacon.go, analysis/beacon/beacon_test.go, analysis/blacklisted/blacklisted.go, analysis/crossref/crossref.go, analysis/dns/explodedDNS.go, analysis/dns/hostnames.go, analysis/scanning/scan.go, analysis/structure/hosts.go, analysis/structure/uconn.go, analysis/urls/url.go, analysis/useragent/useragent.go, database/control.go, datatypes/beacon/beacon.go, datatypes/crossref/crossref.go, datatypes/data/data.go, datatypes/dns/dns.go, datatypes/structure/structure.go, parser/mongodatastore.go
Change createCollection to accept mongo indexes. Created better indexes on a bunch of collections.
=> Remove _id indexes Fixes #65

config/config.go, database/resources.go, etc/rita.yaml
=> Enable a Custom Socket Timeout

etc/rita.yaml
=> Update UseDates description for timezone behavior. Fixes #112.

commands/commands.go, commands/show-beacons.go, commands/show-bl-hostname.go, commands/show-bl-ip.go, commands/show-bl-url.go, commands/show-explodedDns.go, commands/show-long-connections.go, commands/show-scans.go, commands/show-urls.go, commands/show-user-agents.go
This PR adds csv headers to rita output and outputs proper csv wrapping fields in quotes when needed.
Fixes #107
=> Output Proper CSV Fixes #107

database/resources.go
Addresses https://github.com/ocmdev/rita/issues/152
We will want to look at alternate solutions going forward
=> Adding ,nil to fix the version issue with the newest changes to lfshook

install.sh
Subsumes https://github.com/ocmdev/rita/pull/155
=> HOTFIX: Fix interactive shell hacks, implemented per branch installer

install.sh
Merge dev installer into master with per branch installation. https://github.com/ocmdev/rita/pull/156
=> HOTFIX: Update installer for master

install.sh
Fixes issue #144 
I have tested this script in docker on Ubuntu 16.04, Ubuntu 14.04, and CentOS 7. I have not tested the new installer on Security Onion yet.
=> Support CentOS

install.sh
The security onion installer breaks when we source the bashrc file if the posix flag is not set.
=> Add security onion patch; support centos

config/config.go, etc/rita.yaml, install.sh
* Change config file location to `/etc/rita/`
* Change the rita install location to `/opt/rita`
* Adding additional command line parameters for script and developer flexibility. These are meant to be undocumented so I didn't update the rita help text.
* Disable bro installation
* Disable mongo installation
* Change the install location
=> Updated default install and config locations

etc/rita.yaml, install.sh
* Change permissions of bro's default log directory to allow non-root users to read as well.
* UseDates wasn't getting activated before. Using a DefaultDatabase will activate UseDates functionality.
=> Updating default config

Gopkg.toml
Point the rita-bl dependency back to master.
=> ActiveCM Rename Part 2

commands/show-scans.go
=> Fix the ports display on show scans

install.sh, tests/helpers.sh, tests/install.bats
Please review it once. To check if bro is working i tried bro -h command and for mongodb just mongo command in the terminals after the restart.
=> bro mongo start on boot

install.sh
New Features:
- Activate bash tab autocomplete (#259)
- Adding error message if there's a problem with the RITA version number (#253)
- Allow Analysis While Importing Separate Data (for IPFIX ingest) (#260)
Checks and Tests:
The installer has been left relatively unchanged since v1.0.3, so installation tests should pass easily.
```
diff --git a/install.sh b/install.sh
index afc8fc9..f4b26ff 100755
--- a/install.sh
+++ b/install.sh
@@ -4,7 +4,7 @@
-_RITA_VERSION="v1.0.3"
+_RITA_VERSION="v1.1.0"
_NAME=$(basename "${0}")
_FAILED="\e[91mFAILED\e[0m"
_SUCCESS="\e[92mSUCCESS\e[0m"
@@ -339,6 +339,9 @@ __install_rita() {
touch "$_VAR_PATH/safebrowsing"
chmod 755 "$_VAR_PATH"
chmod 666 "$_VAR_PATH/safebrowsing"
+
+       mkdir -p /etc/bash_completion.d/
+       curl -sSL …
```
=> Update installer to v1.1.0

analysis/structure/hosts.go, analysis/structure/uconn.go, datatypes/structure/structure.go
=> Add max duration fields to uconn and host collections

install.sh
=> removed prompt to request to add bro to the path, now added by default

analysis/structure/uconn.go, datatypes/structure/structure.go
Field was accidentally removed in the last update
#316
=> added missing total duration field back into uconns

config/static.go, config/static_test.go, config/testing.go, etc/rita.yaml, install.sh, parser/fsimporter.go
#308 
I fix hardcoding connLimit to be configurable with `ConnectionLimit` in mongoDBCfg
please review it.
=> Move connection limit to mongoDB conf #308

Readme.md, etc/rita.yaml
=> basic filtering documentation

Gopkg.lock, commands/commands.go, resources/logging.go, util/util.go
The issue did not specify the format of the logged message so I made one up.
Everything else went swimingly
Closes #292
=> Fix #292: Change Logging directory structure

Gopkg.lock, commands/import.go, parser/filter.go, parser/filter_test.go, parser/fsimporter.go
Fixes #337 by checking if the `InternalSubnets` list is empty. This avoids classifying all IPs as external and filtering them out by default.
I revised the tests to cover more cases, including the ones this PR fixes, and to print a useful message to identify failing test cases.  Here is the relavant output of the tests before this fix was implemented.
```
=== RUN   TestFilterConnPairWithInternalSubnets
--- PASS: TestFilterConnPairWithInternalSubnets (0.00s)
=== RUN   TestFilterConnPairWithoutInternalSubnets
--- FAIL: TestFilterConnPairWithoutInternalSubnets (0.00s)
filter_test.go:110: 
Error Trace:	filter_test.go:110
Error:      	Not equal: 
expected: false
actual  : true
Test:       	TestFilterConnPairWithoutInternalSubnets
Messages:   	internal to internal should not be filtered when …
```
=> Refuse to run import if InternalSubnets is not configured

commands/show-bl-hostname.go, commands/show-bl-ip.go, parser/fsimporter.go, pkg/beacon/repository.go, pkg/host/analyzer.go, pkg/host/mongodb.go, pkg/host/repository.go, pkg/hostname/analyzer.go, pkg/hostname/repository.go, pkg/uconn/repository.go, reporting/report-bl-dest-ips.go, reporting/report-bl-hostnames.go, reporting/report-bl-source-ips.go, reporting/templates/templates.go
=> 364 blacklisted analysis to importer

parser/fsimporter.go, pkg/beacon/analyzer.go, pkg/beacon/mongodb.go, pkg/beacon/mongodb_test.go, pkg/beacon/repository.go, pkg/host/analyzer.go, pkg/host/mongodb.go, pkg/host/mongodb_test.go, pkg/host/repository.go, pkg/uconn/analyzer.go, pkg/uconn/mongodb.go, pkg/uconn/mongodb_test.go, pkg/uconn/repository.go
updated hosts for dashboard, fixed blacklisted error, added txt query count for source host
=> Host updates for dashboard

Gopkg.lock, commands/show-explodedDns.go, config/static.go, config/static_test.go, config/testing.go, etc/rita.yaml, parser/fsimporter.go, pkg/explodeddns/analyzer.go, pkg/explodeddns/mongodb.go, pkg/explodeddns/repository.go, reporting/report-explodedDns.go
took out storing list of subdomains, replaced with count, updated command line results and reporting, took out config limits out of yaml and config related files
=> Update exploded dns subdomain storage

parser/fsimporter.go, pkg/host/analyzer.go, pkg/uconn/repository.go
=> added verification for well-known service on well-known port

commands/import.go, database/meta.go
=> added error and check for import directory not existing

parser/fsimporter.go, parser/parsetypes/ssl.go, pkg/useragent/analyzer.go, pkg/useragent/mongodb.go, pkg/useragent/repository.go, pkg/useragent/writer.go
=> add ja3 to useragent and rare useragent/j3 count to hosts

commands/show-long-connections.go, commands/show-strobes.go, database/meta.go, parser/fsimporter.go, parser/mongodatastore.go, pkg/host/analyzer.go, pkg/uconn/analyzer.go, pkg/uconn/repository.go
=> update longconns to v3

pkg/beacon/analyzer.go, pkg/beacon/mongodb.go
=> added conn count metric to replace duration in beacon analysis

database/meta.go, parser/fsimporter.go, parser/mongodatastore.go, pkg/beacon/analyzer.go, pkg/beacon/mongodb.go
=> fixed error, beacon analysis is all better now

install.sh
Turn on certificate logging for certificate analysis.
=> Enable SSL certificate logging

commands/show-beacons.go
Remove Intvl Duration from human readable output in show-beacons as the metric was removed.
Ensure headers match between csv and human readable output in show-beacons.
=> 422 fix beacon headers in v3

install.sh, test-install.sh
=> Removing code for Ubuntu 14.04

commands/show-bl-hostname.go, commands/show-bl-ip.go, commands/show-explodedDns.go, commands/show-long-connections.go, commands/show-strobes.go, commands/show-user-agents.go, pkg/blacklist/analyzer.go, pkg/useragent/analyzer.go, reporting/report-bl-dest-ips.go, reporting/report-bl-hostnames.go, reporting/report-explodedDns.go, reporting/report-long-connections.go, reporting/report-strobes.go, reporting/report-useragents.go
=> updated to allow disk use in all pipe queries

parser/fsimporter.go
Fix certificate count missing check if exists #477
=> fix certificate count missing check if exists #477

docs/Bro Install From Source.md, docs/RITA Gittiquette.md
=> moved "Bro Install From Source" and "RITA Gittiquette" from wiki to docs folder

commands/import.go, commands/import_test.go, database/meta.go
=> Allowing databases to increase the number of chunks

Readme.md, docker-compose.yml, docs/Docker Usage.md, docs/Manual Installation.md, docs/System Requirements.md
Got feedback from a couple users that the install process wasn't straightforward. This revision is to help that a little bit, though there might be more work to be done in the installer.
Also updated the docker documentation to support the latest version.
=> Revise install documentation

reporting/report-beacons.go, reporting/report-bl-dest-ips.go, reporting/report-bl-hostnames.go, reporting/report-bl-source-ips.go, reporting/report-explodedDns.go, reporting/report-long-connections.go, reporting/report-strobes.go, reporting/report-useragents.go, reporting/report.go
Fixes empty beacons page stopping html reporting, better handles error reporting internally to the html reporting system
=> Fixes #493, improvements to error reporting on page creation

Readme.md
There are no longer special instructions for working with Security Onion.
https://github.com/activecm/rita/issues/146#issuecomment-579006135
=> Update readme to reflect json import

Contributing.md, docs/RITA Gittiquette.md
Our workflow, both internally and accepting contributions, has changed since we last updated the documentation.
Closes #532
=> Updating contributing documentation to align with current workflow

parser/indexedfile.go
Added info error that tells the user that a log has failed to index when a file errors out during indexing. RITA continues to execute after this error.
Added info error that tells the user that all of the logs passed in are empty or incompatible if none of the logs were able to be indexed. RITA then exits with an exit code of zero.
Testing:
When there is a log that is empty/incompatible, but there are other non-empty/compatible logs to import:
When there are no logs that are compatible or all logs are empty:
Closes #553
=> Exit when all logs to import are empty

Readme.md, docs/Rolling Datasets.md
Addresses: https://github.com/activecm/rita/issues/556
=> Updating usage docs to make rolling use cases more clear

parser/fsimporter.go
There's a slight speedup when testing with a small dataset. This savings should scale with the size of the dataset. In the output below `rita-reflect` represents the master branch and `rita-assert` represents these changes. I ran each import a couple times just to make sure the times were close.
```
./rita-reflect import ignore/empire-raw reflect  16.08s user 3.68s system 191% cpu 10.308 total
./rita-reflect import ignore/empire-raw reflect2  15.79s user 3.64s system 192% cpu 10.106 total
./rita-assert import ignore/empire-raw assert  14.80s user 3.50s system 192% cpu 9.505 total
./rita-assert import ignore/empire-raw assert2  14.62s user 3.72s system 181% cpu 10.080 total
```
But that's just the cherry on the top. The biggest benefit is increased code readability.
Thanks @Zalgo2462 for …
=> Replace reflect with type assertions in import

config/static.go, config/static_test.go, etc/rita.yaml, go.mod, go.sum, pkg/blacklist/service.go
See https://github.com/activecm/rita-bl/pull/9 for a full description.
=> Update threat intel feeds

commands/show-beacons-fqdn.go
=> Fix human readable labels in show-beacons-fqdn

pkg/beaconfqdn/dissector.go
hotfix for bug on not being able to record fqdn beacons that are also ip beacons
=> beacons fqdn bug hotfix

.github/workflows/release.yml, commands/show-beacons.go, pkg/beacon/analyzer.go, pkg/beacon/repository.go, reporting/report-beacons.go, reporting/templates/templates.go
I made it so the total bytes per connection shows up in the show-beacons command and html-report.  builds and passes tests.
=> Added TotalBytes to show-beacons and html-report

install.sh
Update rita version in `install.sh` as mentioned in https://github.com/activecm/rita/blob/master/docs/Releases.md
=> Update installer version to v4.2.0

parser/fsimporter.go, pkg/remover/mongodb.go
fixed missing chunk removal for invalid certificate table, fixed logic for adding cert records to uconns
Closes: #633
=> Invalid certificates bugs

install.sh
This mirrors what we do in docker-zeek.
=> extend zeek inactivity timeout.

install.sh
Update version in installer to 4.3.1
=> Update version to 4.3.1

pkg/host/mongodb.go
Adding in some more indexes to the hosts collection to allow for faster lookup of some items.
=> Add Additional Indexes to Hosts Collection for Faster Lookups

.github/workflows/release.yml, .github/workflows/test.yml, Dockerfile, go.mod, go.sum, test.Dockerfile
Updated the Go version to Go 1.17, ran go mod tidy, and built the docker images.
=> Update to go 1.17

install.sh
Removes the spaces in the variable assignment on line 526
=> Remove spaces from line 526

pkg/beaconproxy/dissector.go
- fixed breaking proxy beacons aggregtion step typo
=> Breaking proxy beacon aggregation

pkg/beacon/summarizer.go, pkg/beaconfqdn/summarizer.go, pkg/beaconproxy/summarizer.go, pkg/beaconsni/summarizer.go, pkg/uconn/summarizer.go
Currently, as a part of the IP beacons, FQDN beacons, SNI beacons, proxy beacons, and connection time analyses, the highest scoring destination for each internal host is recorded in the `host` collection.  This is done after each import, and for rolling datasets, there will be a `dat.max_xxx_score` subdocument for each analysis and each rolling chunk/ CID. 
If the same destination comes up as the highest scorer in separate rolling imports, a subdocument will be created for each CID. 
This makes it difficult to associate these subdocuments with the most recent analysis results. For example, consider the case when a beacon score for a particular internal host and destination decreases over time but it remains the highest scoring beacon for that internal host. In this case, there will be …
=> Ensure there is only a single `max_$ANALYSIS_score` subdocument per destination in the `host` collection

install.sh
=> Bump to v4.7.0

commands/show-beacons-proxy.go, config/static.go, config/static_test.go, config/testing.go, etc/rita.yaml, pkg/beaconproxy/analyzer.go, pkg/beaconproxy/repository.go, reporting/report-beaconsproxy.go, reporting/templates/templates.go
- Updated Beacon Proxy to use new scoring metrics
- Added yaml weights for scoring
- updated command line and html reporting
=> Update Beacons Proxy Scoring

parser/fsimporter.go
Currently, if a user disables the SNI beacon analysis, the user will still have to wait for the SNI connection analysis to finish even though the data will not be used for anything. 
This PR ensures that RITA skips the SNI connection analysis if the SNI beaocn analysis is disabled.
=> Disable SNI connection analysis if SNI beacon analysis is disabled

install.sh
=> Bump version
